"""PDF executive report generation using ReportLab.

Builds a compact executive summary PDF:

- title, generation date and API/report metadata
- KPI summary table
- category highlights
- top products by inventory value
- key observations derived from the actual data

The generator consumes the SAME KPI results produced by
``KPIEngine.calculate_all()`` (and the same processed DataFrame) used by the
Excel report, so both reports stay consistent.
"""

from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional

import pandas as pd

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import cm
from reportlab.platypus import (
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from ..config import REPORT_VERSION, OutputConfig, config
from ..reports.excel_report import CURRENCY, DECIMAL2, INTEGER, KPI_META, PERCENT
from ..utils.exceptions import PDFReportError
from ..utils.logger import setup_logger

logger = setup_logger(__name__)

# ── Colors ─────────────────────────────────────────────────────
DARK_BLUE = colors.HexColor("#1F3864")
LIGHT_BLUE = colors.HexColor("#D6E4F0")
LIGHT_GREY = colors.HexColor("#F2F2F2")
BORDER_GREY = colors.HexColor("#B0B0B0")

# ── Page layout ────────────────────────────────────────────────
MARGIN = 2 * cm
PAGE_W, PAGE_H = A4

# ── Paragraph styles ───────────────────────────────────────────
TITLE_STYLE = ParagraphStyle(
    "Title", fontName="Helvetica-Bold", fontSize=20, leading=24,
    textColor=DARK_BLUE, alignment=TA_CENTER, spaceAfter=4,
)
SUBTITLE_STYLE = ParagraphStyle(
    "Subtitle", fontName="Helvetica-Oblique", fontSize=11, leading=14,
    textColor=colors.HexColor("#595959"), alignment=TA_CENTER, spaceAfter=4,
)
GENERATED_STYLE = ParagraphStyle(
    "Generated", fontName="Helvetica", fontSize=9, leading=12,
    textColor=colors.grey, alignment=TA_CENTER,
)
SECTION_STYLE = ParagraphStyle(
    "Section", fontName="Helvetica-Bold", fontSize=13, leading=16,
    textColor=DARK_BLUE, spaceBefore=14, spaceAfter=6,
)
BODY_STYLE = ParagraphStyle(
    "Body", fontName="Helvetica", fontSize=10, leading=14,
    alignment=0, spaceAfter=6,
)
BULLET_STYLE = ParagraphStyle(
    "Bullet", fontName="Helvetica", fontSize=10, leading=14,
    leftIndent=14, bulletIndent=4, spaceAfter=3,
)

# ── Value formatting ───────────────────────────────────────────
# Matching the Excel format strings so both reports display the same figures.
FORMATTERS = {
    CURRENCY: lambda v: f"${v:,.2f}",
    INTEGER: lambda v: f"{v:,.0f}",
    DECIMAL2: lambda v: f"{v:.2f}",
    PERCENT: lambda v: f"{v:.1f}%",
}


def _format_value(value: Any, fmt: Optional[str]) -> str:
    """Format a value using the shared Excel-style format strings."""
    if value is None or (isinstance(value, float) and pd.isna(value)):
        return "-"
    formatter = FORMATTERS.get(fmt)
    try:
        return formatter(value) if formatter else str(value)
    except (TypeError, ValueError):
        return str(value)


def _shorten(text: Any, limit: int = 45) -> str:
    """Trim over-long display text (e.g. product titles)."""
    text = str(text)
    return text if len(text) <= limit else f"{text[: limit - 3]}..."


def _table(
    data: List[list],
    col_widths: Optional[List[float]] = None,
    right_align_cols: Optional[List[int]] = None,
) -> Table:
    """Build a professionally styled PDF table with a dark header row."""
    table = Table(data, colWidths=col_widths, hAlign="LEFT", repeatRows=1)
    style = [
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("BACKGROUND", (0, 0), (-1, 0), DARK_BLUE),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("GRID", (0, 0), (-1, -1), 0.5, BORDER_GREY),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, LIGHT_GREY]),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("LEFTPADDING", (0, 0), (-1, -1), 5),
        ("RIGHTPADDING", (0, 0), (-1, -1), 5),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ]
    for col in right_align_cols or []:
        style.append(("ALIGN", (col, 1), (col, -1), "RIGHT"))
    table.setStyle(TableStyle(style))
    return table


def _draw_footer(canvas, doc) -> None:
    """Print a footer with report version and page number on every page."""
    canvas.saveState()
    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(colors.grey)
    canvas.drawString(
        MARGIN, 1.1 * cm,
        f"Generated by Automated Business Reporting Engine (v{REPORT_VERSION})",
    )
    canvas.drawRightString(PAGE_W - MARGIN, 1.1 * cm, f"Page {doc.page}")
    canvas.restoreState()


class PDFReportGenerator:
    """Generates an executive summary PDF from KPI engine output."""

    def __init__(self, output_config: Optional[OutputConfig] = None):
        """Initialize with output configuration (defaults to app config)."""
        self.output_config = output_config or config.output
        self.pdf_dir = Path(self.output_config.pdf_dir)
        self.report_name = self.output_config.report_name

    # ── Public API ──────────────────────────────────────────────

    def generate(
        self,
        df: pd.DataFrame,
        kpis: Dict[str, Any],
        metadata: Optional[Dict[str, Any]] = None,
    ) -> Path:
        """
        Build the executive summary PDF.

        Args:
            df: Cleaned product DataFrame.
            kpis: Output of ``KPIEngine.calculate_all()``.
            metadata: Optional info dict (api_source, record_count, ...).

        Returns:
            Path to the generated PDF.

        Raises:
            PDFReportError: On empty data or missing KPI results.
        """
        logger.info("Generating PDF report")
        if df is None or len(df) == 0:
            raise PDFReportError(
                "Cannot generate a PDF report from an empty dataset."
            )
        required_kpis = {"general", "category", "products"}
        if not isinstance(kpis, dict) or not required_kpis <= set(kpis):
            raise PDFReportError(
                "kpis must contain 'general', 'category' and 'products' "
                "(use KPIEngine.calculate_all())."
            )

        now = datetime.now()
        meta = self._normalize_metadata(metadata or {}, df, now)

        try:
            self.pdf_dir.mkdir(parents=True, exist_ok=True)
        except OSError as exc:
            raise PDFReportError(
                f"Cannot create output directory {self.pdf_dir}: {exc}"
            ) from exc

        filepath = self.pdf_dir / f"{self.report_name}_{now:%Y-%m-%d}.pdf"
        story = self._build_story(df, kpis, meta, now)

        doc = SimpleDocTemplate(
            str(filepath),
            pagesize=A4,
            leftMargin=MARGIN,
            rightMargin=MARGIN,
            topMargin=MARGIN,
            bottomMargin=MARGIN,
            title=meta["report_title"],
            author="Automated Business Reporting Engine",
        )
        try:
            doc.build(story, onFirstPage=_draw_footer, onLaterPages=_draw_footer)
        except Exception as exc:  # noqa: BLE001 - surface any build failure
            filepath.unlink(missing_ok=True)  # remove any partial output
            raise PDFReportError(f"Failed to save PDF report: {exc}") from exc

        logger.info(f"PDF report saved to {filepath}")
        return filepath

    # ── Metadata ────────────────────────────────────────────────

    def _normalize_metadata(
        self, metadata: Dict[str, Any], df: pd.DataFrame, now: datetime
    ) -> Dict[str, Any]:
        meta = dict(metadata)
        meta.setdefault("report_title", self.report_name)
        meta.setdefault("report_version", REPORT_VERSION)
        meta.setdefault("api_source", str(config.api.url))
        meta.setdefault("record_count", int(len(df)))
        meta.setdefault("generation_timestamp", f"{now:%Y-%m-%d %H:%M:%S}")
        return meta

    # ── Story assembly ──────────────────────────────────────────

    def _build_story(
        self,
        df: pd.DataFrame,
        kpis: Dict[str, Any],
        meta: Dict[str, Any],
        now: datetime,
    ) -> List[Any]:
        """Assemble the report flowables in reading order."""
        story = [
            Paragraph(meta["report_title"], TITLE_STYLE),
            Paragraph(
                "Automated Business Reporting Engine - Executive Summary",
                SUBTITLE_STYLE,
            ),
            Paragraph(
                f"Generated: {now:%Y-%m-%d %H:%M:%S}    |    "
                f"Data Source: {meta['api_source']}",
                GENERATED_STYLE,
            ),
            Spacer(1, 6),
            Paragraph("Executive Summary", SECTION_STYLE),
            Paragraph(self._summary_text(df, kpis, meta), BODY_STYLE),
            Paragraph("Key Performance Indicators", SECTION_STYLE),
            self._kpi_table(kpis),
            Spacer(1, 10),
            Paragraph("Category Highlights", SECTION_STYLE),
            self._category_table(kpis),
            Spacer(1, 10),
            Paragraph("Top Products by Inventory Value", SECTION_STYLE),
            self._top_products_table(kpis),
            Spacer(1, 10),
            Paragraph("Key Observations", SECTION_STYLE),
        ]
        for observation in self._observations(df, kpis):
            story.append(
                Paragraph(observation, BULLET_STYLE, bulletText="\u2022")
            )
        story.append(Paragraph("Report Metadata", SECTION_STYLE))
        story.append(self._metadata_table(meta))
        return story

    def _summary_text(
        self, df: pd.DataFrame, kpis: Dict[str, Any], meta: Dict[str, Any]
    ) -> str:
        """Honest, factual summary paragraph based only on source data."""
        general = kpis["general"]
        return (
            f"This executive report summarizes the product catalog retrieved "
            f"from {meta['api_source']} at the time of generation. It covers "
            f"{general['total_products']:,} products across "
            f"{len(kpis['category']):,} categories. All figures are derived "
            f"directly from the source data and include no estimated sales, "
            f"revenue or customer information."
        )

    def _kpi_table(self, kpis: Dict[str, Any]) -> Table:
        """Two-column KPI summary, using the same metric set as Excel."""
        general = kpis["general"]
        rows = [("Metric", "Value")]
        for key, label, fmt in KPI_META:
            rows.append((label, _format_value(general.get(key), fmt)))
        return _table(rows, col_widths=[7 * cm, 5 * cm], right_align_cols=[1])

    def _category_table(self, kpis: Dict[str, Any]) -> Table:
        """Top 10 categories by inventory value."""
        category = kpis["category"].sort_values(
            "inventory_value", ascending=False
        ).head(10)
        rows = [("Category", "Products", "Avg Price", "Inventory Value")]
        for _, record in category.iterrows():
            rows.append(
                (
                    str(record["category"]),
                    _format_value(record["product_count"], INTEGER),
                    _format_value(record["average_price"], CURRENCY),
                    _format_value(record["inventory_value"], CURRENCY),
                )
            )
        return _table(
            rows,
            col_widths=[4.5 * cm, 2.2 * cm, 2.6 * cm, 3.2 * cm],
            right_align_cols=[1, 2, 3],
        )

    def _top_products_table(self, kpis: Dict[str, Any]) -> Table:
        """Top 5 products by inventory value."""
        top = kpis["products"]["top_by_inventory_value"].head(5)
        rows = [("Product", "Category", "Price", "Stock", "Inventory Value")]
        for _, record in top.iterrows():
            rows.append(
                (
                    _shorten(record["title"]),
                    str(record["category"]),
                    _format_value(record["price"], CURRENCY),
                    _format_value(record["stock"], INTEGER),
                    _format_value(record["inventory_value"], CURRENCY),
                )
            )
        return _table(
            rows,
            col_widths=[5.4 * cm, 3.0 * cm, 2.2 * cm, 1.8 * cm, 3.0 * cm],
            right_align_cols=[2, 3, 4],
        )

    def _observations(self, df: pd.DataFrame, kpis: Dict[str, Any]) -> List[str]:
        """Facts derived strictly from the dataset and the KPI engine."""
        general = kpis["general"]
        category = kpis["category"]
        products = kpis["products"]
        observations: List[str] = []

        observations.append(
            f"A total of {general['total_products']:,} products were analyzed "
            f"across {len(category):,} categories."
        )

        top_count = category.loc[category["product_count"].idxmax()]
        observations.append(
            f'The category with the most products is "{top_count["category"]}" '
            f"with {top_count['product_count']:,} products."
        )

        top_value = category.loc[category["inventory_value"].idxmax()]
        observations.append(
            f'"{top_value["category"]}" holds the highest inventory value by '
            f"category at {_format_value(top_value['inventory_value'], CURRENCY)}."
        )

        top_product = products["top_by_inventory_value"].iloc[0]
        observations.append(
            f'The product with the highest inventory value is '
            f'"{_shorten(top_product["title"])}" at '
            f"{_format_value(top_product['inventory_value'], CURRENCY)}."
        )

        low_product = products["lowest_stock"].iloc[0]
        observations.append(
            f'The product with the lowest stock is "{_shorten(low_product["title"])}" '
            f"with {_format_value(low_product['stock'], INTEGER)} units."
        )

        if "stock_status" in df.columns:
            counts = df["stock_status"].value_counts().to_dict()
            out_of_stock = int(counts.get("out_of_stock", 0))
            observations.append(
                f"{out_of_stock:,} product(s) are currently out of stock and "
                f"{general['low_stock_count']:,} are flagged as low stock."
            )
        else:
            observations.append(
                f"{general['low_stock_count']:,} products are flagged as low stock."
            )

        top_rated = products["top_by_rating"].iloc[0]
        observations.append(
            f'The highest rated product is "{_shorten(top_rated["title"])}" '
            f"at {_format_value(top_rated['rating'], DECIMAL2)} / 5."
        )

        return observations

    def _metadata_table(self, meta: Dict[str, Any]) -> Table:
        rows = [
            ("Report Name", meta["report_title"]),
            ("Report Version", meta["report_version"]),
            ("API Source", meta["api_source"]),
            ("Generation Timestamp", meta["generation_timestamp"]),
            ("Number of Records", f"{meta['record_count']:,}"),
            ("Report Type", "Product Catalog / Inventory Overview"),
        ]
        return _table(rows, col_widths=[5 * cm, 8 * cm], right_align_cols=None)


def generate_pdf_report(
    df: pd.DataFrame,
    kpis: Dict[str, Any],
    metadata: Optional[Dict[str, Any]] = None,
    output_config: Optional[OutputConfig] = None,
) -> Path:
    """Convenience wrapper for generating the PDF report."""
    return PDFReportGenerator(output_config=output_config).generate(df, kpis, metadata)